name: PvPToggle
version: ${project.version}
main: com.pvptoggle.PvPTogglePlugin
api-version: 1.18
authors: [PvPToggle]
description: Allow players to toggle PvP on and off.

commands:
  pvp:
    description: Toggle your PvP status.
    usage: /pvp
    aliases: [pvptoggle]
    permission: pvptoggle.use

permissions:
  pvptoggle.use:
    description: Allows players to toggle their PvP status.
    default: true
